-- JBC ATHENAEUM Stage 1 production hardening.
-- This migration is additive and data-preserving. The legacy profiles.role
-- column remains in place for rollback/verification, but is no longer writable
-- or trusted for authorization.

begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  faculty text,
  role text default 'scholar',
  created_at timestamptz not null default now()
);

create table if not exists public.resources (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  subject text not null,
  faculty text not null,
  semester text not null,
  author_name text not null,
  author_id uuid references public.profiles(id) on delete set null,
  file_url text not null,
  file_size text,
  resource_type text default 'PDF',
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscriptions (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

do $$
begin
  create type public.app_role as enum (
    'student',
    'contributor',
    'faculty',
    'moderator',
    'admin',
    'super_admin'
  );
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.app_role not null,
  granted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_roles_user_id_role_key unique (user_id, role)
);

create index if not exists user_roles_user_id_idx on public.user_roles(user_id);
create index if not exists user_roles_role_idx on public.user_roles(role);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_events_created_at_idx
  on public.audit_events(created_at desc);
create index if not exists audit_events_actor_id_idx
  on public.audit_events(actor_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists user_roles_set_updated_at on public.user_roles;
create trigger user_roles_set_updated_at
before update on public.user_roles
for each row execute function public.set_updated_at();

-- Backfill missing profiles without copying email addresses into public data.
insert into public.profiles (id, name, faculty)
select
  users.id,
  coalesce(
    nullif(trim(users.raw_user_meta_data ->> 'name'), ''),
    nullif(split_part(users.email, '@', 1), ''),
    'Scholar'
  ),
  coalesce(nullif(trim(users.raw_user_meta_data ->> 'faculty'), ''), 'Unknown')
from auth.users as users
on conflict (id) do nothing;

-- The legacy profiles.role field was client-writable, so it is preserved for
-- owner review but never promoted into a trusted membership automatically.
insert into public.user_roles (user_id, role)
select users.id, 'student'::public.app_role
from auth.users as users
on conflict (user_id, role) do nothing;

create or replace function public.has_role(
  required_role public.app_role
)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.user_roles
    where user_roles.user_id = auth.uid()
      and user_roles.role = required_role
  );
$$;

revoke all on function public.has_role(public.app_role) from public;
grant execute on function public.has_role(public.app_role) to anon, authenticated;

create or replace function public.is_platform_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.has_role('admin'::public.app_role)
      or public.has_role('super_admin'::public.app_role);
$$;

revoke all on function public.is_platform_admin() from public;
grant execute on function public.is_platform_admin() to anon, authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, name, faculty)
  values (
    new.id,
    coalesce(
      nullif(trim(new.raw_user_meta_data ->> 'name'), ''),
      nullif(split_part(new.email, '@', 1), ''),
      'Scholar'
    ),
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'faculty'), ''), 'Unknown')
  )
  on conflict (id) do nothing;

  insert into public.user_roles (user_id, role)
  values (new.id, 'student'::public.app_role)
  on conflict (user_id, role) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.set_user_role(
  target_user_id uuid,
  target_role public.app_role,
  should_grant boolean default true
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor uuid := auth.uid();
  actor_is_admin boolean;
  actor_is_super_admin boolean;
begin
  if actor is null then
    raise exception using errcode = '42501', message = 'Authentication is required';
  end if;

  actor_is_admin := public.has_role('admin'::public.app_role);
  actor_is_super_admin := public.has_role('super_admin'::public.app_role);

  if target_role in ('admin'::public.app_role, 'super_admin'::public.app_role) then
    if not actor_is_super_admin then
      raise exception using errcode = '42501', message = 'Only a super administrator can change privileged roles';
    end if;
  elsif not (actor_is_admin or actor_is_super_admin) then
    raise exception using errcode = '42501', message = 'Administrator role is required';
  end if;

  if actor = target_user_id
     and target_role in ('admin'::public.app_role, 'super_admin'::public.app_role) then
    raise exception using errcode = '42501', message = 'Privileged self-role changes are not allowed';
  end if;

  if not should_grant and target_role = 'super_admin'::public.app_role then
    if (
      select count(*)
      from public.user_roles
      where role = 'super_admin'::public.app_role
    ) <= 1 then
      raise exception using errcode = '23514', message = 'The final super administrator cannot be removed';
    end if;
  end if;

  if should_grant then
    insert into public.user_roles (user_id, role, granted_by)
    values (target_user_id, target_role, actor)
    on conflict (user_id, role) do nothing;
  else
    delete from public.user_roles
    where user_id = target_user_id and role = target_role;
  end if;

  insert into public.audit_events (
    actor_id,
    action,
    entity_type,
    entity_id,
    metadata
  ) values (
    actor,
    case when should_grant then 'role.granted' else 'role.revoked' end,
    'user',
    target_user_id,
    jsonb_build_object('role', target_role, 'granted', should_grant)
  );
end;
$$;

revoke all on function public.set_user_role(uuid, public.app_role, boolean) from public;
grant execute on function public.set_user_role(uuid, public.app_role, boolean) to authenticated;

create or replace function public.subscribe_to_newsletter(subscriber_email text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  normalized_email text := lower(trim(subscriber_email));
  inserted_count integer;
begin
  if normalized_email is null
     or length(normalized_email) > 254
     or normalized_email !~* '^[A-Z0-9._%+\-]+@[A-Z0-9.\-]+\.[A-Z]{2,}$' then
    raise exception using errcode = '22023', message = 'A valid email address is required';
  end if;

  insert into public.newsletter_subscriptions (email)
  values (normalized_email)
  on conflict (email) do nothing;

  get diagnostics inserted_count = row_count;
  return inserted_count = 1;
end;
$$;

revoke all on function public.subscribe_to_newsletter(text) from public;
grant execute on function public.subscribe_to_newsletter(text) to anon, authenticated;

-- Remove legacy policies before installing the least-privilege policy set.
do $$
declare
  policy_record record;
begin
  for policy_record in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in (
        'profiles',
        'user_roles',
        'resources',
        'newsletter_subscriptions',
        'audit_events'
      )
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      policy_record.policyname,
      policy_record.schemaname,
      policy_record.tablename
    );
  end loop;
end
$$;

alter table public.profiles enable row level security;
alter table public.profiles force row level security;
alter table public.user_roles enable row level security;
alter table public.user_roles force row level security;
alter table public.resources enable row level security;
alter table public.resources force row level security;
alter table public.newsletter_subscriptions enable row level security;
alter table public.newsletter_subscriptions force row level security;
alter table public.audit_events enable row level security;
alter table public.audit_events force row level security;

create policy profiles_select_own_or_admin
on public.profiles for select to authenticated
using (auth.uid() = id or public.is_platform_admin());

create policy profiles_insert_own
on public.profiles for insert to authenticated
with check (auth.uid() = id);

create policy profiles_update_own
on public.profiles for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy user_roles_select_own_or_admin
on public.user_roles for select to authenticated
using (auth.uid() = user_id or public.is_platform_admin());

create policy resources_public_read
on public.resources for select to anon, authenticated
using (true);

create policy resources_admin_insert
on public.resources for insert to authenticated
with check (public.is_platform_admin());

create policy resources_admin_update
on public.resources for update to authenticated
using (public.is_platform_admin())
with check (public.is_platform_admin());

create policy resources_admin_delete
on public.resources for delete to authenticated
using (public.is_platform_admin());

create policy newsletter_admin_read
on public.newsletter_subscriptions for select to authenticated
using (public.is_platform_admin());

create policy audit_events_admin_read
on public.audit_events for select to authenticated
using (public.is_platform_admin());

-- RLS controls rows; column grants prevent a profile owner from changing the
-- deprecated role column even if the policy permits updating their own row.
revoke all on table public.profiles from anon, authenticated;
grant select (id, name, faculty, avatar_url, bio, created_at, updated_at)
  on public.profiles to authenticated;
grant insert (id, name, faculty, avatar_url, bio)
  on public.profiles to authenticated;
grant update (name, faculty, avatar_url, bio)
  on public.profiles to authenticated;

revoke all on table public.user_roles from anon, authenticated;
grant select (id, user_id, role, granted_by, created_at, updated_at)
  on public.user_roles to authenticated;

revoke all on table public.resources from anon, authenticated;
grant select on table public.resources to anon, authenticated;
grant insert, update, delete on table public.resources to authenticated;

revoke all on table public.newsletter_subscriptions from anon, authenticated;
grant select on table public.newsletter_subscriptions to authenticated;

revoke all on table public.audit_events from anon, authenticated;
grant select on table public.audit_events to authenticated;

comment on column public.profiles.role is
  'Deprecated compatibility field. Authorization uses public.user_roles only.';
comment on function public.set_user_role(uuid, public.app_role, boolean) is
  'Trusted, audited role mutation boundary; privileged roles require super_admin.';
comment on function public.subscribe_to_newsletter(text) is
  'Validated newsletter subscription boundary. Add edge rate limiting in Stage 2.';

commit;
